// Plot defines

// Zerlinda's Woe
const string PLT_ORZ400PT_ZERLINDA = "87AFF6349A0447B485A18D786E58682B";
	const int ORZ_ZERLINDA___PLOT_01_ACCEPTED_FATHER = 0;
	const int ORZ_ZERLINDA_CONVINCED = 2;
	const int ORZ_ZERLINDA___PLOT_03_COMPLETED_GONE_TO_CHANTRY = 3;
	const int ORZ_ZERLINDA___PLOT_02_REJECTED_FATHER = 4;
	const int ORZ_ZERLINDA___PLOT_03_COMPLETED_GONE_TO_FAMILY_HAPPY = 5;
	const int ORZ_ZERLINDA_PC_LEFT_EARLY = 6;
	const int ORZ_ZERLINDA_IS_MAD_AT_PC = 7;
	const int ORZ_ZERLINDA___PLOT_02_AGREED_FATHER = 8;
	const int ORZ_ZERLINDA___PLOT_REFUSED = 9;
	const int ORZ_ZERLINDA___PLOT_02_AGREED_BURKEL = 10;
	const int ORZ_ZERLINDA___PLOT_01_ACCEPTED_BURKEL = 11;
	const int ORZ_ZERLINDA___PLOT_03_COMPLETED_GONE_TO_SURFACE = 12;
	const int ORZ_ZERLINDA_TOLD_HER_STORY = 13;
	const int ORZ_ZERLINDA___PLOT_02_REJECTED_BURKEL = 14;
	const int ORZ_ZERLINDA___PLOT_FAILED = 15;
	const int ORZ_ZERLINDA_PC_GIVES_CASH_LOW = 16;
	const int ORZ_ZERLINDA_PC_GIVES_CASH_HIGH = 17;
	const int ORZ_ZERLINDA___PLOT_ACTIVE = 256;
	const int ORZ_ZERLINDA_PC_HAS_CASH_HIGH = 257;
	const int ORZ_ZERLINDA_PC_HAS_CASH_LOW = 258;
	const int ORZ_ZERLINDA_PC_CAN_ASK_BURKEL = 259;
	const int ORZ_ZERLINDA_PC_GAVE_MONEY = 260;
	const int ORZ_ZERLINDA___PLOT_03_COMPLETED = 261;
