// Plot defines

// Thief in the House of Learning
const string PLT_ORZ310PT_THIEF = "2C50728792CD464E82C27F3512C8E511";
	const int ORZ_THIEF_PLOT_ACCEPTED = 0;
	const int ORZ_THIEF_FOUND_PROVING_RECEIPT = 1;
	const int ORZ_THIEF_RECOVERED_STOLEN_TOME = 2;
	const int ORZ_THIEF_PLOT_COMPLETED_TOME_RETURNED = 3;
	const int ORZ_THIEF_PLOT_COMPLETED_TOME_SOLD = 4;
	const int ORZ_THIEF_BOSS_ATTACKS = 5;
	const int ORZ_THIEF_PC_HAS_STOLEN_TOME = 256;
