// Plot defines

// Wynne's Regret
const string PLT_GENPT_WYNNE_MAIN = "0F78D9FC6FBD4183A1243DDC1BBE5D01";
	const int WYNNE_MAIN_PC_KNOWS_WYNNE_DEAD = 0;
	const int WYNNE_MAIN_PC_KNOWS_WYNNE_TIRED = 1;
	const int WYNNE_MAIN_DISCUSSED_ABOMINATIONS = 2;
	const int WYNNE_MAIN_TALKED_TO_ANEIRIN = 3;
	const int WYNNE_MAIN_TALKED_ABOUT_SERVING = 4;
	const int WYNNE_MAIN_PRESENT_WHEN_JOWAN_MET = 5;
	const int WYNNE_MAIN_PRESENT_WHEN_CONNOR_MET = 6;
	const int WYNNE_MAIN_PC_HEARD_ABOUT_ANEIRIN = 7;
	const int WYNNE_MAIN_DISCUSSED_BECOMING_GREY_WARDEN = 8;
	const int WYNNE_MAIN_PC_KNOWS_WHY_SPIRIT_CHOSE_HER = 9;
	const int WYNNE_MAIN_TALKED_ABOUT_DUTY = 10;
	const int WYNNE_MAIN_TALKED_ABOUT_CURE = 11;
	const int WYNNE_MAIN_TALKED_ABOUT_HISTORY = 12;
	const int WYNNE_MAIN_ALISTAIR_KNOWS_WYNNE_SON = 13;
	const int WYNNE_MAIN_HEARD_ANEIRIN_ALIVE = 14;
	const int WYNNE_MAIN_SPIRIT_FORM_STAGE_A = 15;
	const int WYNNE_MAIN_SPIRIT_FORM_STAGE_B = 16;
	const int WYNNE_MAIN_SPIRIT_FORM_STAGE_C = 17;
	const int WYNNE_MAIN_MOVES_TO_CAMP_WAYPOINT = 18;
	const int WYNNE_MAIN_JUST_BEFORE_LANDSMEET = 256;
	const int WYNNE_MAIN_CONNOR_KNOWN_BUT_NOT_DONE = 257;
	const int WYNNE_MAIN_CAN_ASK_ABOUT_CONNOR_PLAN = 258;
	const int WYNNE_MAIN_JOWAN_MET_PLOT_IN_PROGRESS = 259;
	const int WYNNE_MAIN_PC_IS_IN_A_ROMANCE = 260;
	const int WYNNE_MAIN_CAN_ASK_ABOUT_TIRED = 261;
	const int WYNNE_MAIN_READY_FOR_WHAT_GREY_WARDEN_MEANS = 262;
	const int WYNNE_MAIN_READY_FOR_GREY_WARDEN_HISTORY = 263;
	const int WYNNE_MAIN_IN_PARTY_AND_PC_HEARD_ABOUT_ANEIRIN = 264;
	const int WYNNE_MAIN_IN_PARTY_BUT_CIRCLE_PLOT_NOT_DONE = 265;
