// Plot defines

// Betrayed from Within
const string PLT_ORZPT_WFBHELEN_DA = "1CB806624C2E431CB4303A0C6582BCFB";
	const int ORZ_WFBDA___PLOT_01_ACCEPTED = 0;
	const int ORZ_WFBDA___PLOT_04_COMPLETED = 1;
	const int ORZ_WFBDA___PLOT_FAILED = 3;
	const int ORZ_WFBDA_MISSED_CHANCE = 4;
	const int ORZ_WFBDA___PLOT_03_PAPERS_PLANTED = 5;
	const int ORZ_WFBDA___PLOT_REFUSED = 6;
	const int ORZ_WFBDA___PLOT_02_JARVIA_KILLED = 7;
	const int ORZ_WFBDA___PLOT_PRE_PLOT_01_TT_HARROW = 8;
	const int ORZ_WFBDA___PLOT_PRE_PLOT_02_RETURN_TO_VARTAG = 9;
	const int ORZ_WFBDA___PLOT_ACTIVE = 256;
	const int ORZ_WFBDA_PC_FAILED_TO_PLANT_PAPERS = 257;
