// Plot defines

// Of Noble Birth
const string PLT_ORZ300PT_NOBHUNTER = "C93EAEA757434D5A893E7D7E2F636F8A";
	const int ORZ_NOBHUNTER___PLOT_01_ACCEPTED = 0;
	const int ORZ_NOBHUNTER___PLOT_FAILED = 1;
	const int ORZ_NOBHUNTER___PLOT_04_COMPLETED = 2;
	const int ORZ_NOBHUNTER_PC_DOES_NOT_KNOW = 3;
	const int ORZ_NOBHUNTER___PLOT_REFUSED = 4;
	const int ORZ_NOBHUNTER_PC_GIVES_DONATION_CHEAP = 5;
	const int ORZ_NOBHUNTER_PC_GIVES_DONATION_NORMAL = 6;
	const int ORZ_NOBHUNTER_PC_GIVES_DONATION_SIZABLE = 7;
	const int ORZ_NOBHUNTER_PC_GIVES_DONATION_SUBSTANTIAL = 8;
	const int ORZ_NOBHUNTER___PLOT_02A_BHELEN_PROMISED = 9;
	const int ORZ_NOBHUNTER___PLOT_02C_HARROWMONT_PROMISED = 10;
	const int ORZ_NOBHUNTER___PLOT_03_PROMISE = 11;
	const int ORZ_NOBHUNTER___PLOT_02B_BHELEN_AGREED = 13;
	const int ORZ_NOBHUNTER___PLOT_02D_HARROWMONT_AGREED = 14;
	const int ORZ_NOBHUNTER_BHELEN_REFUSED = 15;
	const int ORZ_NOBHUNTER_HARROWMONT_REFUSED = 16;
	const int ORZ_NOBHUNTER___PLOT_ACTIVE = 256;
	const int ORZ_NOBHUNTER_BHELEN_MENTIONED = 257;
	const int ORZ_NOBHUNTER_BHELEN_NEVER_MENTIONED = 258;
	const int ORZ_NOBHUNTER_ACTIVE_NOTPROMISED = 259;
	const int ORZ_NOBHUNTER_PC_HAS_DONATION_CHEAP = 261;
	const int ORZ_NOBHUNTER_PC_HAS_DONATION_NORMAL = 262;
	const int ORZ_NOBHUNTER_PC_HAS_DONATION_SIZABLE = 263;
	const int ORZ_NOBHUNTER_PC_HAS_DONATION_SUBSTANTIAL = 264;
	const int ORZ_NOBHUNTER_IS_IN_NOBLES_QUARTER = 267;
