// Plot defines

// Queen Anora
const string PLT_COD_CHA_ANORA = "73B42D576B61441DB6C3E730A5308151";
	const int COD_CHA_ANORA_MAIN = 0;
	const int COD_CHA_ANORA_RESCUE = 1;
	const int COD_CHA_ANORA_RESCUE_BETRAYED = 2;
	const int COD_CHA_ANORA_SACRIFICE = 3;
	const int COD_CHA_ANORA_RESCUE_FIGHT = 4;
	const int COD_CHA_ANORA_POSTRESCUE = 5;
	const int COD_CHA_ANORA_SUPPORTS_PC_VICTORY = 6;
	const int COD_CHA_ANORA_BETRAYS_PC = 7;
	const int COD_CHA_ANORA_SUPPORTS_PC_FAILURE = 8;
	const int COD_CHA_ANORA_PC_WINS_LANDSMEET = 9;
	const int COD_CHA_ANORA_PC_LOSES_LANDSMEET = 10;
	const int COD_CHA_ANORA_PC_WINS_LANDSMEET_NOFIGHT = 11;
	const int COD_CHA_ANORA_QUEEN_ALISTAIR_DEAD = 12;
	const int COD_CHA_ANORA_MARRIES_PC_ALISTAIR_DEAD = 13;
	const int COD_CHA_ANORA_MARRIES_PC_ALISTAIR_LEAVES = 14;
	const int COD_CHA_ANORA_MARRIES_PC_ALISTAIR_STAYS = 15;
	const int COD_CHA_ANORA_QUEEN_ALISTAIR_STAYS = 16;
	const int COD_CHA_ANORA_QUEEN_ALISTAIR_LEAVES = 17;
	const int COD_CHA_ANORA_MARRIES_ALISTAIR_AL_STAYS = 18;
	const int COD_CHA_ANORA_MARRIES_ALISTAIR_AL_LEAVES = 19;
	const int COD_CHA_ANORA_DEPOSED = 20;
