// Plot defines

// An Unlikely Scholar
const string PLT_ORZ200PT_DAGNA = "3324ED085FC640308F8753382634149E";
	const int ORZ_DAGNA___PLOT_01_ACCEPTED = 0;
	const int ORZ_DAGNA__REWARD_SERUM = 1;
	const int ORZ_DAGNA___PLOT_03_COMPLETED = 2;
	const int ORZ_DAGNA_LEFT_ORZAMMAR_FOR_TOWER = 3;
	const int ORZ_DAGNA_JANAR_DISAPPROVES = 4;
	const int ORZ_DAGNA_PC_WAS_PROMISED_REWARD = 5;
	const int ORZ_DAGNA___PLOT_REFUSED = 6;
	const int ORZ_DAGNA___PLOT_02_IRVING_ACCEPTED = 7;
	const int ORZ_DAGNA_PC_HAS_GONE_TO_TOWER_AFTER_ACCEPTING = 8;
	const int ORZ_DAGNA_JANAR_KNOWS = 9;
	const int ORZ_DAGNA_JANAR_IS_MAD = 10;
	const int ORZ_DAGNA___PLOT_FAILED = 11;
	const int ORZ_DAGNA__REWARD_RUNE = 12;
	const int ORZ_DAGNA_PC_ASKED_JANAR_ABOUT_DAGNA = 13;
	const int ORZ_DAGNA___PLOT_02_GREAGOIR_REFUSED = 14;
	const int ORZ_DAGNA___PLOT_ACTIVE = 256;
	const int ORZ_DAGNA_PC_CAN_ASK_JANAR_ABOUT_DAUGHTER = 257;
	const int ORZ_DAGNA_PC_CAN_GIVE_DAGNA_ANSWER = 259;
