// Plot defines

// Fazzil's Request
const string PLT_DEN200PT_FAZZIL_REQUEST = "BEE2360A38664B4D8719276A1CB1FB32";
	const int FAZZIL_CHANTER_BOARD = 0;
	const int FAZZIL_ACCEPTED = 1;
	const int FAZZIL_SEXTANT_RECOVERED = 2;
	const int FAZZIL_QUEST_DONE = 3;
	const int JOURNAL_SEXTANT_RECOVERED_SANS_QUEST = 4;
	const int JOURNAL_SEXTANT_RECOVERED_WITH_QUEST = 5;
