// Plot defines

// Darkspawn Invasion
const string PLT_CIR320PT_DARKSPAWN = "FC403D6258E24207AD525265BFDD8F39";
	const int DARKSPAWN_QUEST_ACTIVE = 0;
	const int DARKSPAWN_TEMPLAR_FOUND = 1;
	const int DARKSPAWN_TEMPLAR_GIVES_FORM = 2;
	const int DARKSPAWN_QUEST_DONE = 3;
	const int DARKSPAWN_GOLEM_DOOR_CLEARED = 4;
