// Plot defines

// Lady in Waiting
const string PLT_DEN200PT_THIEF_PICK1 = "D5297F9D2AED4F90A4D016EBF1DB7EFC";
	const int THIEF_PICK1_ASSIGNED = 0;
	const int THIEF_PICK1_TAKE_FEE = 1;
	const int THIEF_PICK1_SUCCESSFUL = 2;
	const int MAID_CAUGHT_PC_STEALING = 3;
	const int MAID_CAUGHT_STEALING_DIALOG_READY = 4;
	const int THIEF_PICK1_PC_HAS_MONEY = 256;
