// Plot defines

// qwinn_approval
const string PLT_QWINN_APPROVAL = "B1351F0C4D934D039DF06458BA4C9273";
	const int MORRIGAN_ULTIMATUM_CHOSE_LELIANA = 0;
	const int LELIANA_ULTIMATUM_CHOSE_MORRIGAN = 1;
	const int ZEVRAN_GET_IN_THE_TENT = 2;
	const int PRE_RECRUIT_MORRIGAN_TOGGLE = 3;
	const int QW_ROMANCE_ACTIVE_ALISTAIR = 256;
	const int QW_ROMANCE_ACTIVE_MORRIGAN = 257;
	const int QW_ROMANCE_ACTIVE_LELIANA = 258;
	const int QW_ROMANCE_ACTIVE_ZEVRAN = 259;
	const int QW_DUMPED_MORRIGAN_FOR_LELIANA_AND_IN_LOVE_LELIANA = 260;
	const int QW_DUMPED_LELIANA_FOR_MORRIGAN_AND_IN_LOVE_MORRIGAN = 261;
	const int QW_MORRIGAN_IN_LOVE_LELIANA_ROMANCE_NOT_ACTIVE = 262;
	const int QW_PC_MALE_MORRIGAN_ROMANCE_CAN_RESTART = 263;
	const int QW_ALISTAIR_NOT_ROMANCED_NOT_WARM = 264;
	const int QW_FEMALE_LELIANA_IS_IN_LOVE = 265;
	const int QW_ALISTAIR_ROMANCE_ACTIVE_DID_NOT_MAKE_LOVE = 266;
