// Plot defines

// The Ransom
const string PLT_DEN200PT_ASSASSIN_END = "C9913BA344A14BF992EA905B2E8D7930";
	const int ASSASSIN_END_QUEST_ACCEPTED = 0;
	const int ASSASSIN_END_QUEST_DONE = 1;
	const int ASSASSIN_LAST_TARGET_KILLED = 2;
	const int ASSASSIN_END_PAYMENT_TAKEN = 3;
	const int IGNACIO_MENTIONED_KIDNAPPED_BOY = 4;
	const int ASSASSIN_END_REWARD_PLACED = 5;
	const int CHASE_SPOOKED_BY_PC = 6;
	const int CHASE_ATTACKS = 7;
	const int CROWS_LEAVE_RANDSOM_AREA = 8;
