// Plot defines

// The Dwarven Veteran
const string PLT_ARL130PT_RECRUIT_DWYN = "919D9962FBC346BF9054D7798CCEDB80";
	const int ARL_RECRUIT_DWYN_MURDOCK_KNOWS_DWYN_DEAD = 0;
	const int ARL_RECRUIT_DWYN_DWYN_IS_DEAD = 1;
	const int ARL_RECRUIT_DWYN_DWYN_HELPING = 2;
	const int ARL_RECRUIT_DWYN_PC_HEARD_ABOUT_DWYN = 3;
	const int ARL_RECRUIT_DWYN_DWYN_INTIMIDATED = 4;
	const int ARL_RECRUIT_DWYN_DWYN_TOLD_PC_HE_WONT_HELP = 5;
	const int ARL_RECRUIT_DWYN_DWYN_TOLD_PC_HES_BOARDED_UP = 6;
	const int ARL_RECRUIT_DWYN_PC_PAYS_FULL_TO_HIRE_DWYN = 7;
	const int ARL_RECRUIT_DWYN_PC_PAYS_HALF_TO_HIRE_DWYN = 8;
	const int ARL_RECRUIT_DWYN_DWYN_INTIMIDATED_TO_FIGHT = 9;
	const int ARL_RECRUIT_DWYN_DWYN_LEAVES_PERMANENTLY = 10;
	const int ARL_RECRUIT_DWYN_OUTSIDE_AMBIENT = 11;
	const int ARL_RECRUIT_DWYN_PC_FIGHTS_DWYN = 12;
	const int ARL_RECRUIT_DWYN_DOOR_IS_UNLOCKED = 13;
	const int ARL_RECRUIT_DWYN_GIVES_LOCKBOX_KEY = 14;
	const int ARL_RECRUIT_DWYN_FAILED = 15;
	const int ARL_RECRUIT_DWYN_DWYN_DEAD_AND_MURDOCK_NOT_TOLD = 256;
	const int ARL_RECRUIT_DWYN_DWYN_NOT_DEAD_AND_NOT_HELPING = 257;
	const int ARL_RECRUIT_DWYN_PC_CAN_AFFORD_TO_PAY_DWYN_TO_HELP = 258;
	const int ARL_RECRUIT_DWYN_PC_CAN_AFFORD_TO_PAY_DWYN_HALF = 259;
	const int ARL_RECRUIT_DWYN_DWYN_PAID_TO_FIGHT = 260;
	const int ARL_RECRUIT_DWYN_PC_MET_DWYN = 261;
