// Plot defines

// A Stolen Seed
const string PLT_NTB220PT_GRAND_OAK = "0CC09B0997E64041BD39DE12E34FC875";
	const int NTB_GRAND_OAK_HEART_PLOT_ACCEPTED = 0;
	const int NTB_GRAND_OAK_PC_GOES_HOSTILE = 1;
	const int NTB_GRAND_OAK_GIVES_HEART_REWARD = 2;
	const int NTB_GRAND_OAK_MENTIONED_HEART = 3;
	const int NTB_GRAND_OAK_KILLED = 4;
	const int NTB_GRAND_OAK_HEART_PLOT_DONE = 5;
	const int NTB_GRAND_OAK_PC_ACQUIRED_HEART_FROM_HERMIT = 6;
	const int NTB_GRAND_OAK_PC_HAS_HEART = 7;
	const int NTB_GRAND_OAK_ACORN_STOLEN_FROM_TREE = 8;
	const int NTB_GRAND_OAK_ACORN_STOLEN_NOT_MET_TREE = 9;
	const int NTB_GRAND_OAK_PC_ACQUIRED_HEART_NOT_MET_TREE = 10;
	const int NTB_GRAND_OAK_REPLACEMENT = 11;
	const int NTB_GRAND_OAK_MENTIONED_HEART_AND_ALIVE = 256;
	const int NTB_GRAND_OAK_MENTIONED_HEART_AND_KILLED = 257;
	const int NTB_GRAND_OAK_MENTIONED_HEART_AND_PLOT_ACCEPTED = 258;
	const int NTB_GRAND_OAK_MENTIONED_HEART_AND_PLOT_NOT_ACCEPTED = 259;
	const int NTB_GRAND_OAK_MENTIONED_HEART_AND_NOT_YET_POSSESSED = 260;
